#!/usr/bin/ruby

require 'fileutils'
require 'yaml'

base = File.expand_path(File.dirname(__FILE__))
tmp = File.join(base, 'tmp')

FileUtils.mkdir_p(tmp)

# target maildir
maildir = File.join(tmp,'Mail')
FileUtils.mkdir_p(File.join(maildir, 'new'))
FileUtils.mkdir_p(File.join(maildir, 'cur'))
FileUtils.mkdir_p(File.join(maildir, 'tmp'))

cache = File.join(tmp, 'cache')

case ARGV.length
when 0
  config_data = <<EOF
cache: #{cache}
feeds:
  - name: CNPQ
    url: http://www.cnpq.br/web/guest/noticias/-/asset_publisher/6QsO/rss?p_p_cacheability=cacheLevelPage
    target: maildir://#{maildir}
  - name: XKCD
    url: http://www.xkcd.com/atom.xml
    target: maildir://#{maildir}
EOF
when 1
  config_data = <<EOF
cache: #{cache}
feeds:
  - name: Test
    url: #{ARGV.first}
    target: maildir://#{maildir}
EOF
else
  puts("usage: %s [FEED]" % $PROGRAM_NAME)
  exit(1)
end

config = File.join(tmp, 'feed2imap.yaml')
File.open(config, 'w') do |f|
  f.write(config_data)
end
FileUtils.chmod 0600, config

unless system('ruby', "-I#{base}/lib", "#{base}/bin/feed2imap", '--config', config, '--debug')
  puts("E: feed2imap failed")
  exit(1)
end

print "Open target maildir with mutt? [Y/n]"
response = $stdin.gets.strip
if response.downcase == 'y' || response == ''
  exec('mutt', '-f', maildir)
end
