#!/usr/bin/ruby

require 'fileutils'
require 'yaml'
require 'uri'
require 'digest/sha1'

base = File.expand_path(File.dirname(__FILE__))
tmp = File.join(base, 'tmp')

FileUtils.mkdir_p(tmp)

# target maildir
maildir = File.join(tmp,'Mail')
FileUtils.mkdir_p(File.join(maildir, 'new'))
FileUtils.mkdir_p(File.join(maildir, 'cur'))
FileUtils.mkdir_p(File.join(maildir, 'tmp'))

target = ENV["TARGET"] || "maildir://#{maildir}"

cache = File.join(tmp, 'cache-' + Digest::SHA1.hexdigest(target))

case ARGV.length
when 0
  config_data = <<EOF
cache: #{cache}
include-images: true
feeds:
  - name: Antonio Terceiro
    url: https://terceiro.xyz/feed.xml
    target: #{target}
    filter: /bin/cat
  - name: Planet Debian (broken filter)
    url: http://planet.debian.org/atom.xml
    target: #{target}
    filter: /bin/epicfail
  - name: XKCD
    url: http://www.xkcd.com/atom.xml
    target: #{target}
  - name: Outras Palavras - Tecnologia em Disputa
    url: https://outraspalavras.net/category/tecnologiaemdisputa/feed/
    target: #{target}
EOF
else
  feeds = ARGV.map do |url|
    {
      "name" => URI.parse(url).hostname,
      "url" => url,
      "target" => target,
    }
  end
  config_data = YAML.dump({
    "cache" => cache,
    "feeds" => feeds,
  })
end

config = File.join(tmp, 'feed2imap.yaml')
File.open(config, 'w') do |f|
  f.write(config_data)
end
FileUtils.chmod 0600, config

unless system('ruby', "-I#{base}/lib", "#{base}/bin/feed2imap", '--config', config, '--verbose')
  puts("E: feed2imap failed")
  exit(1)
end

print "Open target maildir with mutt? [Y/n]"
response = $stdin.gets.strip
if response.downcase == 'y' || response == ''
  target.sub!(%r[^maildir://], '')
  exec('mutt', '-f', target)
end
