.TH feed2imap\-dumpconfig 1 "Jul 25, 2005"  
.SH NAME
feed2imap\-dumpconfig \- Dump feed2imap config
.SH SYNOPSIS
\fBfeed2imap\-dumpconfig\fR [OPTIONS]
.SH DESCRIPTION
feed2imap\-dumpconfig dumps the content of your feed2imaprc to screen.
.TP 
\fB\-f\fR, \fB\-\-config \fIfile\fB\fR 
Use another config file (~/.feed2imaprc is the default).
.SH "SEE ALSO"
Homepage : 
http://home.gna.org/feed2imap/
.PP
\fBfeed2imaprc\fR(5),
\fBfeed2imap\fR(1)
.SH AUTHOR
Copyright (C) 2005 Lucas Nussbaum lucas@lucas\-nussbaum.net
.PP
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 2 of the License, or (at your
option) any later version.
.PP
This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
more details.
