.TH feed2imap\-opmlimport 1 "Jul 25, 2005"  
.SH NAME
feed2imap\-opmlimport \- Convert an OPML subscription list to a feed2imap config file
.SH SYNOPSIS
\fBfeed2imap\-opmlimport\fR
.SH DESCRIPTION
feed2imap\-opmlimport reads an OPML subscription list on standard input and outputs a feed2imap configuration file on standard output. The resulting configuration file will require some tweaking.
.SH BUGS
Should probably accept parameters to be able to change default values.
.SH "SEE ALSO"
Homepage : 
http://home.gna.org/feed2imap/
.PP
\fBfeed2imaprc\fR(5),
\fBfeed2imap\fR(1)
.SH AUTHOR
Copyright (C) 2005 Lucas Nussbaum lucas@lucas\-nussbaum.net
.PP
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 2 of the License, or (at your
option) any later version.
.PP
This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
more details.
